name: webapi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  youtube_player_iframe: ^2.1.0
  youtube_player_flutter: ^8.0.0
  screenshot: ^1.2.1
  crop_image: ^1.0.1
  flutter_speed_dial: ^3.0.5
  flutter_luban: ^0.1.13
  zoomable_image: ^1.3.1
  universal_platform: ^1.0.0+1
  path_provider:
  dependencies:
  crop: ^0.5.1+1
  firebase: ^9.0.1
  dio: ^4.0.0
  syncfusion_flutter_pdf: ^19.1.55-beta
  firebase_storage: ^9.0.0
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  another_flushbar: ^1.10.24
  crop_your_image: ^0.5.3
  image_picker_web_redux: any

dev_dependencies:
  flutter_test:
    sdk: flutter
    
    
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #   - family: Abel
  #     fonts:
  #       - asset: fonts/Abel-Regular.ttf
  #         weight: 200
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Roboto-MediumItalic.ttf
  #         weight: 500
  #       - asset: 
  #         weight: 300
  #   - family: 
  #     fonts:
  #       - asset: fonts/pottaOne-Regular.ttf
  #         weight: 700         
  fonts:
    - family: Abel
      fonts:
        - asset: fonts/Abel-Regular.ttf
          weight: 200
    - family: Roboto
      fonts:      
        - asset: fonts/Roboto-MediumItalic.ttf
          style: italic
        - asset: fonts/Roboto-LightItalic.ttf
          style: italic
    - family: pottaOne
      fonts:
        - asset: fonts/pottaOne-Regular.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
